Решение задания Change data and component routing
sorokinaolga/junior-course-os pull request #10
Opened 2021-09-03 08:59 UTC by sorokinaolga

Отправляю решение 11 раздела 'Change data and component routing'.

2021-09-13 08:28 UTC, vislogurov requested changes

2021-09-13 08:28 UTC, vislogurov commented on src/store/products/reducer.js
> +        // maxValuePrice: maxBy(obj => obj.price, action.payload).price,
Либо пиши зачем эту строку закрмментировали либо совсем удаляй её. Иначе непонятно.

2021-09-13 08:28 UTC, vislogurov commented on src/components/Basket/Basket.js
> +import React from 'react';
Замечания общего характера:
1) http://localhost:3000/cart для чего нужна эта ссылка, если она никуда не ведёт?
2) Обрати внимание, при переходе на вторую страницу и выборе товара меня обратно кидает на первую. Это странно поведение, как минимум пользователь может захотеть выбрать несколько со второй страницы. И его будет каждый раз так «кидать». http://s.csssr.ru/U0FMPH83W/20210913111902.mp4

2021-09-25 04:57 UTC, sorokinaolga commented
Исправила замечания, постаралась отредактировать верстку. Ссылку на корзину оставила, корзину же в следующем задании делаем? Просто там теория сразу на 2 задания открывалась.

2021-09-26 14:10 UTC, vislogurov commented
Да, всё так. Я поторопился чуть, корзина будет дальше конечно))

2021-09-26 14:10 UTC, vislogurov approved these changes

2021-09-27 08:47 UTC, merged