task 'State and uncontrolled components'
sorokinaolga/junior-course-os pull request #3
Opened 2020-12-25 07:46 UTC by sorokinaolga

Закончила раздел "State and uncontrolled components"

2020-12-25 08:16 UTC, vislogurov requested changes

2020-12-25 08:16 UTC, vislogurov commented on src/index.js
> +  priceFilterData = (min, max) => {
render должен быть последнем методом в компоненте, тогда компонент легко читается сверху вниз.

2020-12-25 08:16 UTC, vislogurov commented on src/index.js
> +  constructor(props) {
Предлагаю всю логику с фильтрами перенести в PriceFIlters, тк она не относится ко всему приложению, а только к части фильтров. Тогда App останется чисто корневым компонентов, визуально компонент "разгрузим" и перенесём логику фильтров в зону ответственности фильтров.

На этапе "роутинга" всё равно придётся это сделать, тк из App нужно будет разные роуты рендерить, и такое количество кода в App будет излишним.

2021-03-11 11:17 UTC, sorokinaolga commented
Привет, внесла изменения по замечаниям

2021-03-12 07:54 UTC, vislogurov approved these changes

2021-03-18 07:44 UTC, merged