task Context
sorokinaolga/junior-course-os pull request #5
Opened 2021-04-27 11:45 UTC by sorokinaolga

Завершила работу по разделу Context

2021-04-27 12:29 UTC, vislogurov requested changes

2021-04-27 12:29 UTC, vislogurov commented on src/index.js
> +  setHistoryCategory = () => {
Ты выше в cDM подписываешься на popstate. Он будет доступен в колбэке. Состояние фильтров можно прочитать из него, без костылей проверяющих длину window.location

setHistoryCategory = (event) => ...

2021-04-27 12:29 UTC, vislogurov commented on src/index.js
> +  setHistoryCategory = () => {
https://developer.mozilla.org/ru/docs/Web/API/Window/popstate_event

2021-04-27 12:29 UTC, vislogurov commented on src/index.js
> +  changeFilter = (minValue, maxValue, discount, category) => {
Метод называется `changeFilter` хотя по сути занимается фильтрацией списка

2021-04-29 08:35 UTC, sorokinaolga commented
Вроде все подправила

2021-04-29 08:38 UTC, vislogurov approved these changes

2021-04-29 08:44 UTC, merged