закончила task Redux
sorokinaolga/junior-course-os pull request #6
Opened 2021-05-24 14:30 UTC by sorokinaolga

2021-05-24 15:21 UTC, vislogurov requested changes

2021-05-24 15:21 UTC, vislogurov commented on src/store/reducer.js
> +        ...initialState,
Думаю копия тут лишняя. RESET_FILTER и так подразумевает сброс к initialState

2021-05-24 15:21 UTC, vislogurov commented on src/store/index.js
> +window.history.replaceState({}, '', window.location.pathname);
А почему именно в файле со инициализацией стора? Есть ли смысл делать это, если при первой загрузке стейт и так будет пустой.

2021-05-24 15:21 UTC, vislogurov commented on src/containers/FilterContainer.js
> +    { changeFilter, resetFilter }
Интересное решение) А можешь объяснить подробнее почему предпочтение отдано именно такой форме, а не использованию mapDispatchToProps в явном виде?

2021-05-25 12:55 UTC, sorokinaolga commented
Привет, с замечаниями согласна, убрала лишний код. По поводу mapDispatchToProps: использовала такую запись в другом учебном проекте, сделала аналогично и возможно не самую лучшую практику переняла. Переписала mapDispatchToProps в явный вид.

2021-05-25 12:57 UTC, vislogurov approved these changes

2021-05-25 13:00 UTC, merged