Выполнение задания Redux Modularization
sorokinaolga/junior-course-os pull request #7
Opened 2021-06-01 14:18 UTC by sorokinaolga

2021-06-01 14:51 UTC, vislogurov requested changes

2021-06-01 14:51 UTC, vislogurov commented on src/components/Pagination/Pagination.js
> +      props.handleChangePage(pageNumber);
Каждый раз, когда внутри одного компонента приходится повторять какие-то методы/строки/чтоугодно, то это сигнал к тому, что-то идёт не так.

У тебя оба хендлера делают одно и тоже — пушат в history инфу о текущей странице.

Я предлагаю задизейблить через стили (pointer-events: none) кнопки "Вперёд/Назад". А условием дизейбла будет как раз `pageNumber > 0` или `pageNumber <= props.pages.length`. Тогда клик по ним вполне себе будет отрабатывать через `handlePageClick`.  А копипастный `handleButtonClick` можно будет удалить.

2021-06-01 14:51 UTC, vislogurov commented on src/components/Pagination/Pagination.js
> +      <button className={style.pagination_button} onClick={() => handleButtonClick(props.activePage - 1)}>Назад</button>
В целом это хороший кандидат для выноса в отдельный компонент. Такая кнопка может пригодиться и в форме регистрации, например.

2021-06-01 14:51 UTC, vislogurov commented on src/components/Pagination/Pagination.js
> +              <li key={number}
Если мы по этому кликаем, то почему оно li?

2021-06-01 14:51 UTC, vislogurov commented on src/components/Pagination/Pagination.js
> +  for (let i=1; i<= props.pages.length; i++) {
Это можно сделать чуть красивее `[...Array(props.pages.length)].map(.....)` в отдельном методе или прямо в render.

Да, сейчас и такое решение работает. Но циклы менее декларативны (менее читабельные) чем проход через map.

2021-06-01 14:51 UTC, vislogurov commented on src/store/actions.js
> +const changeFilter = (name, value) => store.dispatch({ type: types.CHANGE_FILTER, payload: { name: name, value: value } });
Вот тут хотелось бы развёрнутый комментарий, почему используется store.dispatch, вместо mapDispatchToProps.

2021-06-01 15:01 UTC, vislogurov commented on src/store/actions.js
> +const changeFilter = (name, value) => store.dispatch({ type: types.CHANGE_FILTER, payload: { name: name, value: value } });
https://react-redux.js.org/using-react-redux/connect-mapdispatch#can-i-call-storedispatch
Информация к размышлению)))

2021-06-07 16:09 UTC, sorokinaolga commented
Отредактировала компонент Pagination: убрала лишний хендлер, заменила li на button. Переписала actions, спасибо за статью, если честно запуталась с редаксом и диспатчами.

2021-06-08 06:41 UTC, vislogurov approved these changes

2021-06-08 08:59 UTC, merged