Выполнила задание 'Роутинг'
sorokinaolga/junior-course-os pull request #8
Opened 2021-06-16 18:04 UTC by sorokinaolga

2021-06-17 08:52 UTC, vislogurov requested changes

2021-06-17 08:52 UTC, vislogurov commented on src/containers/CardsContainer.js
> +      minPrice: state.filters.minPrice,
Ниже в FilterContainer ты те же самые поля получаешь, кажется это можно вынести в отдельный селектор

2021-06-17 08:52 UTC, vislogurov commented on src/components/ProductPage/ProductPage.js
> +import products from '../../products.json';
Почему это делается напрямую из json, а не из стора?

2021-06-18 09:30 UTC, sorokinaolga commented
Добавила компоненту ProductPage компонент контейнер, добавила селекторы.

2021-06-18 10:03 UTC, vislogurov approved these changes

2021-06-18 10:15 UTC, merged