Выполнила задание раздела API
sorokinaolga/junior-course-os pull request #9
Opened 2021-06-21 07:41 UTC by sorokinaolga

2021-06-22 07:22 UTC, vislogurov requested changes

2021-06-22 07:22 UTC, vislogurov commented on src/components/Header/Header.js
> +    return <h1 className={style.title}>{props.title}</h1>;
А что изменилось? Children API позволяет вообще не париться над способом передачи контента, а теперь передача контента жёстко зашита в пропс,

2021-06-22 07:22 UTC, vislogurov commented on src/App.js
> +    this.props.fetchProducts();
А он точно тут нужен? Получается сейчас всё приложения ждёт загрузки продуктов, хотя по факту они нужны только для контейнера списка.

P.S не нужно сразу бросаться переписывать, хочу понять ход мыслей)

2021-06-22 07:22 UTC, vislogurov commented on src/containers/ProductContainer.js
> +        {!this.props.isLoading && !this.props.isError && !this.props.item && <NotFound title='Товар не найден' />}
`!this.props.item` это ведь не когда не найден, а когда товара нет. А не найден, это когда пользователь по несуществующему урлу перешёл. Какая-то непрозрачная проверка

2021-06-23 08:59 UTC, sorokinaolga commented
Вернула children в Header. Переписала кейсы в ProductContainer. Не стала fetch переписывать, так как в рамках данного учебного проекта не вижу смысла.

2021-06-24 06:34 UTC, vislogurov requested changes

2021-06-24 06:34 UTC, vislogurov commented on src/containers/ProductContainer.js
> +    const loading = this.props.isLoading && !this.props.isError;
А если ли смысл в этих проверках тут? у тебе же в Main уже есть они, и если там уже succes будет true, то и в этом компоненте он тоже будет true.

2021-06-24 09:32 UTC, sorokinaolga commented on src/containers/ProductContainer.js
> +    const loading = this.props.isLoading && !this.props.isError;
Согласна, если из каталога (Main) переходить на страницу отдельного товара проверки лишние. Но если страницу отдельного товара сразу открывать проверки нужны.

2021-06-24 09:43 UTC, sorokinaolga commented on src/containers/ProductContainer.js
> +    const loading = this.props.isLoading && !this.props.isError;
> А если ли смысл в этих проверках тут? у тебе же в Main уже есть они, и если там уже succes будет true, то и в этом компоненте он тоже будет true.

Согласна, если из каталога (Main) переходить на страницу отдельного товара проверки лишние. Но если страницу отдельного товара сразу открывать проверки нужны.

2021-06-24 09:44 UTC, vislogurov commented on src/containers/ProductContainer.js
> +    const loading = this.props.isLoading && !this.props.isError;
Кажется тут нужен отдельный компонент Page, который инкапсулирует в себе эти проверки, тогда сможем уйти от копипасты

2021-06-24 11:35 UTC, sorokinaolga commented
Добавила компонент Page, перенесла обработку статусов запроса туда.

2021-06-24 11:37 UTC, vislogurov approved these changes

2021-06-24 11:45 UTC, merged